### ISSUE TITLE
GHA docs fail to build for pcdsdaq

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdaq#121]
```
sphinx-autogen -o source/generated source/*.rst
[autosummary] generating autosummary for: source/ami_api.rst, source/ami_basic.rst, source/daq_api.rst, source/daq_basic.rst, source/daq_config.rst, source/env.rst, source/index.rst, source/misc.rst, source/plans_basic.rst, source/preprocessors_api.rst, source/releases.rst, source/scan_pvs.rst, source/sim.rst
[autosummary] writing to source/generated
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/pcdshub/pcdsdaq/actions/runs/4670719716/jobs/8270801611#step:15:17)/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/generate.py", line 396, in generate_autosummary_docs
    name, obj, parent, modname = import_by_name(entry.name)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 654, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named pcdsdaq.daq.check_connect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/sphinx-autogen", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/generate.py", line 639, in main
    generate_autosummary_docs(args.source_file, args.output_dir,
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/generate.py", line 401, in generate_autosummary_docs
    name, obj, parent, modname = import_ivar_by_name(entry.name)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 713, in import_ivar_by_name
    real_name, obj, parent, modname = import_by_name(name, prefixes, grouped_exception)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 654, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named pcdsdaq.daq
make: *** [Makefile:[23](https://github.com/pcdshub/pcdsdaq/actions/runs/4670719716/jobs/8270801611#step:15:24): html] Error 1
Error: Process completed with exit code 2.
```

**Comment by ZLLentz** [comment]
- psdaq isn't on pypi, we install it via a special conda recipe that avoids installing the _entire_ daq
- pcdsdaq needs to be updated to not require the import e.g. #118
